-- ============================================================================
-- ORGINO GROUP - CRIAÇÃO DA TABELA DE RASTREAMENTO E CONTROLE DE VISUALIZAÇÕES
-- ============================================================================
-- Execute este script no SQL Editor do seu painel Supabase.
-- ----------------------------------------------------------------------------

-- 1. Criar a tabela de logs de visualizações
CREATE TABLE IF NOT EXISTS public.video_views_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id BIGINT NOT NULL REFERENCES public.videos_feed(id) ON DELETE CASCADE,
    affiliate_id BIGINT REFERENCES public.user_profiles(id) ON DELETE SET NULL,
    viewer_ip TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Adicionar coluna views_count na tabela de vídeos se não existir
ALTER TABLE public.videos_feed ADD COLUMN IF NOT EXISTS views_count INTEGER DEFAULT 0;

-- 3. Habilitar RLS na tabela de logs
ALTER TABLE public.video_views_logs ENABLE ROW LEVEL SECURITY;

-- 4. Remover políticas antigas se existirem
DROP POLICY IF EXISTS "Permitir leitura de logs para todos" ON public.video_views_logs;
DROP POLICY IF EXISTS "Permitir inserção de logs pública" ON public.video_views_logs;

-- 5. Criar política de leitura pública (necessária para que afiliados consultem suas estatísticas)
CREATE POLICY "Permitir leitura de logs para todos" 
    ON public.video_views_logs 
    FOR SELECT 
    USING (true);

-- 6. Criar política de inserção pública (permite que visitantes anônimos e robôs registrem logs)
CREATE POLICY "Permitir inserção de logs pública" 
    ON public.video_views_logs 
    FOR INSERT 
    WITH CHECK (true);

-- 7. Criar função RPC para gravar visualização de vídeo de forma segura e controlada
CREATE OR REPLACE FUNCTION public.record_video_view(p_video_id bigint, p_affiliate_id bigint DEFAULT NULL)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_ip text;
  v_exists boolean;
BEGIN
  -- Obter IP vindo do cabeçalho da requisição PostgREST
  BEGIN
    v_ip := split_part(coalesce(current_setting('request.headers', true)::json->>'x-forwarded-for', '127.0.0.1'), ',', 1);
  EXCEPTION WHEN OTHERS THEN
    v_ip := '127.0.0.1';
  END;

  -- Verificar se já existe log para este vídeo, este afiliado (ou ambos nulos) e este IP nas últimas 24 horas
  SELECT EXISTS (
    SELECT 1 FROM public.video_views_logs
    WHERE video_id = p_video_id
      AND (affiliate_id = p_affiliate_id OR (affiliate_id IS NULL AND p_affiliate_id IS NULL))
      AND viewer_ip = v_ip
      AND created_at > NOW() - INTERVAL '24 hours'
  ) INTO v_exists;
  
  -- Se não existir visualização desse IP nas últimas 24h, cria o registro e incrementa o contador
  IF NOT v_exists THEN
    INSERT INTO public.video_views_logs (video_id, affiliate_id, viewer_ip)
    VALUES (p_video_id, p_affiliate_id, v_ip);
    
    UPDATE public.videos_feed
    SET views_count = COALESCE(views_count, 0) + 1
    WHERE id = p_video_id;
    
    RETURN true;
  END IF;
  
  RETURN false;
END;
$$;

-- 8. Liberar acesso de execução pública para a função RPC
GRANT EXECUTE ON FUNCTION public.record_video_view(bigint, bigint) TO anon, authenticated;
