CREATE TABLE IF NOT EXISTS public.user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mocha_user_id TEXT UNIQUE NOT NULL, -- Referência ao auth.users.id como texto
    email TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    cpf TEXT,
    phone TEXT,
    role TEXT DEFAULT 'user',
    is_active BOOLEAN DEFAULT TRUE,
    sponsor_id BIGINT,
    company_name TEXT,
    avatar_url TEXT,
    pix_key TEXT,
    pix_type TEXT,
    referral_code TEXT,
    cep TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    number TEXT,
    complement TEXT,
    api_sync_test TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

-- Criar política de leitura
DROP POLICY IF EXISTS "Enable read access for all users" ON public.user_profiles;
CREATE POLICY "Enable read access for all users" ON public.user_profiles FOR SELECT USING (true);

-- Criar política de atualização (O próprio usuário pode se atualizar)
DROP POLICY IF EXISTS "Users can update own profile" ON public.user_profiles;
CREATE POLICY "Users can update own profile" ON public.user_profiles FOR UPDATE USING (auth.uid()::text = mocha_user_id) WITH CHECK (auth.uid()::text = mocha_user_id);


-- Corrigir a função do trigger para não inserir UUID na coluna BIGINT
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.user_profiles (mocha_user_id, email, full_name, role)
  VALUES (
    NEW.id::text,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', 'Usuário Novo'),
    'user'
  );
  RETURN NEW;
END;
$$;
